version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./application:/notesapp/application
    env_file: 
        - .env
  db:
    image: postgres:latest
    restart: always
    container_name: psql
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
        - 5432:5432
    env_file: 
        - .env
volumes:
  pgdata: