version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 notesapp:app
    ports:
      - "5000:5000"
    volumes:
      - ./application:/notesapp/application
    env_file: 
        - .env
    depends_on: 
      - db
  db:
    image: postgres:latest
    restart: always
    container_name: psql
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
        - 5432:5432
    env_file: 
        - .env
volumes:
  pgdata: